[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    name = "Github"
    url = "https://github.com/vineelsai26"
    hrefTargetBlank = true
    weight = 2

[[main]]
    name = "Portfolio"
    url = "https://vineelsai.com/portfolio"
    hrefTargetBlank = true
    weight = 3

[[main]]
    name = "Resume"
    url = "/resume/resume.pdf"
    hrefTargetBlank = true
    weight = 4

[[main]]
    name = "RSS"
    url = "/index.xml"
    hrefTargetBlank = true
    weight = 5
