[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    name = "Portfolio"
    url = "https://portfolio.vineelsai.com"
    hrefTargetBlank = true
    weight = 2

[[main]]
    name = "Github"
    url = "https://github.com/vineelsai26"
    hrefTargetBlank = true
    weight = 3


[[main]]
    name = "RSS"
    url = "/index.xml"
    hrefTargetBlank = true
    weight = 4
